apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server              
          command: [
            "/app/server",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
            ]
          image: docker.pkg.github.com/hnlq715/practice-to-intergrate-k8s/server:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: server-port